//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;

    public partial class Employee
    {
        //public int unique_id { get; set; }
        public string date { get; set; }
        public string dateTimeGMT { get; set; }
        public string team_1 { get; set; }
        public string team_2 { get; set; }
 //       public bool squad { get; set; }
//        public string toss_winner_team { get; set; }
   //     public bool match_started { get; set; }
     //   public  string type{get;set;}
       // public string winner_team { get; set; }
    }
}
